### ISSUE TITLE
Consider to move all Wechaty related repositories to the Org:Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/PMC#1]
To be discussed.

### The List

- [x] wechaty-getting-started
- [x] docker-getting-started
- [x] heroku-getting-started
- [x] wechaty
- [x] wechaty-puppet
- [x] wechaty-puppet-*
- [x] To be added

**Comment by lijiarui** [comment]
Agree, and we may also move third party puppet to wechaty:

- [x] https://github.com/botorange/wechaty-puppet-padplus
- [x] https://github.com/botorange/wechaty-puppet-padpro
- [x] https://github.com/lijiarui/wechaty-puppet-padchat

How do you think about this?

**Comment by huan** [comment]
Yes, if you like to, I'll agree with you.

**Comment by huan** [comment]
@lijiarui I have moved all the related repositories from chatie org to the wechaty org. 

Please close this issue after you moved related repositories from your org, thanks.

**Comment by lijiarui** [comment]
ping @windmemory

**Comment by lijiarui** [comment]
done.
