### ISSUE TITLE
Consider to move docs.chatie.io to wechaty.github.io/docs/

### ISSUE THREAD

**Issue by huan** [wechaty/PMC#2]
To make it a better place to host the docs.

(or find a place other than docs.chatie.io)

**Comment by lijiarui** [comment]
I think we also need a landing page for wechaty now and host this on wechaty.github.io, how do you think about this?

**Comment by huan** [comment]
Yes. It would be great to have a landing page with a professional design.

**Comment by huan** [comment]
I have archived the chatie/docs repository for preparing to move the docs to the wechaty org.

I'd like to just move the chatie/docs to wechaty/docs, and then we use wechaty.github.io/docs/ to visit the wechaty documentation.

This will introduce a breaking change for the URLs:

1. the docs.chatie.io will be reserved for the future chatie documents, and will not be used for wechaty docs anymore.
1. the official wechaty documentation will be hosted at wechaty.github.io/docs/

Please feel free to let me know if you have any questions about this movement.

**Comment by lijiarui** [comment]
No problem, please transfer docs to wechaty org.

But I think we need docs.chatie.io hold on the website for 3 more months.

**Comment by huan** [comment]
1. We have moved the docs from Chatie Org to the Wechaty Org just now. And,
1. We will keep the docs.chatie.io with the current content in the following three months. (say, till **20 Feb 2020**).

Let's start to change the necessary links right now. Thanks.
