### ISSUE TITLE
Consider to move blog.chatie.io to wechaty.github.io/blog/

### ISSUE THREAD

**Issue by huan** [wechaty/PMC#3]
To make it more related to Wechaty itself.

**Comment by lijiarui** [comment]
Vote for not move.

Because blog.chatie.io is talking about the bot and some bot cloud service things...

**Comment by huan** [comment]
Update: finally we move `chatie/blog` (blog.chatie.io) to `wechaty/wechaty.github.io` <https://wechaty.github.io>

There are lots of links to be fixed, consider to write a script to check it out.
