### ISSUE TITLE
Testing-studio will provide Certification for WeChaty Community

### ISSUE THREAD

**Issue by lijiarui** [wechaty/PMC#31]
[TestingStudio](https://www.testing-studio.com/%e6%8a%80%e6%9c%af%e6%9c%8d%e5%8a%a1) is a company whose main business is providing, test training, test service, and test industry communication. It has the tester community ceshiren.com, the industry-recognized Hogwarts Test Academy, and professional enterprise-level customized test services.
 
Today I talked with TestingStudio's founder @seveniruby and he would provide certification for Wechaty as follows:

- Test Scheme
  - Certification:
    - API Certification
    - Performance Certification 
    - Security Certification
  - Service & Support:
    - Continuous Testing
 - Test Report Template
 - Donation to wechaty: https://opencollective.com/wechaty#sponsor

-----

Here is the test service JuziBot provide before, Looking forward to TestingStudio provide a more professional certification in the future!

### Testing Progress Issue
- Alpha Test: https://github.com/wechaty/puppet-services/wiki/Basic-Test 
- Stress Test: https://github.com/wechaty/puppet-services/wiki/Stress-Test 
### Product Test：
- Pass Juzimiaohui Product test: https://github.com/wechaty/puppet-services/wiki/Product-Test 
- Friday Bot can run without any huge problems for more than one week:  https://github.com/wechaty/friday 

Looking forward to the collaboration! Cheers!

**Comment by huan** [comment]
It's great to know that the Wechaty community will have a testing certification partner!

The API and performance testing are all very important for the community to make sure our puppet service can provide the high quality service to all developers.

Welcome TestingStudio , and thank you very much for joining the Wechaty ecosystem and help us improve the quality!

**Comment by seveniruby** [comment]
![image](https://user-images.githubusercontent.com/1222769/125418555-3c1f3b7a-595c-4910-b25e-76998b3cf8d0.png)

**Comment by huan** [comment]
Awesome, thank you very much for supporting Wechaty open source community!

**Comment by huan** [comment]
Close this issue for we have not official start this project in the past years.

The Wechaty community has the plan to create its own certification in the near future, powered by GPT and Friday BOT; any developer can take the test in our [Discord](https://discord.gg/7q8NBZbQzt) and get certificated on Discord with a verified badge, with privileges.
