### ISSUE TITLE
中国开源云联盟2021年度评选

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/PMC#33]
## 中国开源云联盟2021年度开源项目评选

2021 木兰峰会即将以更多元、更开放的姿态全新上线，与此同时中国开源云联盟与木兰开源社区共同推出 2021 杰出开源贡献者、优秀开源项目、最佳开源实践案例、优秀开源创新企业评选活动！

wechaty社区作为一个活跃的开源社区，今年也参与此次评选，申报的项目为“优秀开源项目”。

## 申报初拟信息

* 项目活跃度数据

```text
分析 PR Commit Contributor
wechaty/wechaty 的平均活跃分数为 3.29
-----by grank
```

* 项目技术特点与创新性

wechaty开源项目是一个面向对话自动化的聊天机器人SDK，兼容多种IM平台，如企业微信、微信公众号、钉钉、飞书以及WhatsApp等，同时支持多种变成编程语言，只需要一套代码即可创建运行在多种不同IM平台上的特性，具有多语言、多平台、多插件的丰富特点。
wechaty统一了对话式操作接口，只需要同一套API即可完成对不同类型平台上的对接，未来也将于NLP结合，打造一款让开发者快速编写聊天机器人的框架。

* 项目案例

  - [OSS.Chat: A bridge to the Apache Way in China](https://github.com/kaiyuanshe/osschat)
  - [Rui.BOT: Rui.BOT is an assistant bot for Rui, who is the Founder & CEO of Juzi.BOT.](https://github.com/juzibot/rui-bot)
  - [Friday.Bot: designed for serving the BOT5 Club.](https://github.com/wechaty/friday)
  - [微信每日说](https://github.com/leochen-g/wechatBot)
  - [私人秘书](https://github.com/leochen-g/wechat-assistant)

> 篇幅有限，就只罗列这些

该活动后续涉及到社区答辩环节，所以推荐佳芮代表社区参与答辩，你们觉得如何? @huan  @lijiarui 

* 联系人姓名：李佳芮
* 联系人邮箱：rui@juzi.bot

参考链接：
* [评选公告原文](https://mp.weixin.qq.com/s/Cu2MYw_JMPHPizWSapXuPg)
* [评选申请链接](https://jinshuju.net/f/MBrEba)

**Comment by huan** [comment]
感谢 @wj-Mcat 帮助社区准备材料和推动申请！

我的意见是联系人先留 @lijiarui ，邮箱留社区 mailing list 地址 wechaty@googlegroups.com 。

未来社区答辩的安排，我们再推举对应人选，也欢迎大家自荐。

**Comment by huan** [comment]
Do we have any updates from this application?

**Comment by wj-Mcat** [comment]
Yes, the voting channel will open tomorrow. So let's go ahead to invite developers to vote us tomorrow.

**Comment by huan** [comment]
Awesome, thank you very much for the update!

**Comment by wj-Mcat** [comment]
The [Voting channel](https://mp.weixin.qq.com/s/DeQkIdYv0j3F-czZt7zTJQ) has opened 🎉 🎉 . Let's forward the message to the developer community and invite them to vote. @huan @lijiarui

**Comment by wj-Mcat** [comment]
The final presentation time is coming:  **Oct 25**. All of `wechaty` and `python-wechaty` have an opportunity to give presentation.  What we need to do are a ppt in less than five minutes and qa in less than three minutes which will be given in `tencent online meeting`.

I will give `pre` for `python-wechaty`, and who will give `pre` for `wechaty` ? @huan @lijiarui

**Comment by huan** [comment]
@wj-Mcat Thanks for taking the presentation for Python Wechaty!

@lijiarui would you like to give the presentation for Wechaty? It would be great if you can, or I can prepare it.

**Comment by wj-Mcat** [comment]
The person giving presentation for wechaty has not been decided yet according to the online meeting list. So let's make a choose as soon as possible. @huan @lijiarui

**Comment by huan** [comment]
> 该活动后续涉及到社区答辩环节，所以推荐佳芮代表社区参与答辩

@lijiarui Could you please help @wj-Mcat to confirm whether you can present for the community or not by the end of today so that we will not miss the deadline?

@wj-Mcat we can nominate other contributors if rui has no time for it.

**Comment by lijiarui** [comment]
I have already registered the presentation in the mini-app in Official WeChat Room at 11:00 am today...

I don't think we need to double confirm on GitHub twice.

@wj-Mcat Please pay more attention to the Official WeChat Room confirmation.

**Comment by huan** [comment]
It's great to know that we have registered, thank you very much for all efforts in advocating wechaty to the community.

**Comment by huan** [comment]
It's a great experience that we have joined so many fantastic events!

Close this issue for housekeeping.
