### ISSUE TITLE
重新加入 wechaty 组织

### ISSUE THREAD

**Issue by Ran-Xing** [wechaty/PMC#34]
5月1号的时候       我切换账号到组织        的时候           意外退出了组织，联系了github 支持        说那边也没有权限，需要我重新申请，
PR：[ISSUES](https://github.com/wechaty/jekyll/pull/101)
现在账号是当前账号
麻烦 欢哥 帮我 看看😁

**Comment by huan** [comment]
Ok, before adding you back, please change your contributor name to be the same as your GH name. (@XRSec before)

We will be able to add you back once the contributor name has been fixed.

BTW: I'm curious about what operation you have made as "我切换账号到组织 的时候"
